name: Trigger auto deployment for kontener-app-git-settings-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/kontener-app-git-settings-api-AutoDeployTrigger-8ef10092-eece-40a4-9a6e-bb1c6a69d8af.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KONTENERAPPGITSETTINGSAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KONTENERAPPGITSETTINGSAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KONTENERAPPGITSETTINGSAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/nodejs-microservices
          dockerfilePath: packages/settings-api/Dockerfile
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: kontenerkm.azurecr.io
          registryUsername: ${{ secrets.KONTENERAPPGITGATEWAYAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KONTENERAPPGITGATEWAYAPI_REGISTRY_PASSWORD }}
          containerAppName: kontener-app-git-settings-api
          resourceGroup: szkolenie-KM
          imageToBuild: kontenerkm.azurecr.io/settings-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


